// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCc9XO9rOw69p8XTw95XV4faoBNBRpJDI',
    appId: '1:552541032424:web:8a834391a28ac5a1b65e5d',
    messagingSenderId: '552541032424',
    projectId: 'food-delivery-app-780f4',
    authDomain: 'food-delivery-app-780f4.firebaseapp.com',
    storageBucket: 'food-delivery-app-780f4.appspot.com',
    measurementId: 'G-B8M1X44Q8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzE2q0KISrLlR_tqpTnin769Rze8jB4O0',
    appId: '1:552541032424:android:541b2fcf6636e333b65e5d',
    messagingSenderId: '552541032424',
    projectId: 'food-delivery-app-780f4',
    storageBucket: 'food-delivery-app-780f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuk88NeR4562ah3oJyDTxjFcPGinwUSeU',
    appId: '1:552541032424:ios:3de6e7b55ec7b69cb65e5d',
    messagingSenderId: '552541032424',
    projectId: 'food-delivery-app-780f4',
    storageBucket: 'food-delivery-app-780f4.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuk88NeR4562ah3oJyDTxjFcPGinwUSeU',
    appId: '1:552541032424:ios:3de6e7b55ec7b69cb65e5d',
    messagingSenderId: '552541032424',
    projectId: 'food-delivery-app-780f4',
    storageBucket: 'food-delivery-app-780f4.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCc9XO9rOw69p8XTw95XV4faoBNBRpJDI',
    appId: '1:552541032424:web:0eb6de71a7134000b65e5d',
    messagingSenderId: '552541032424',
    projectId: 'food-delivery-app-780f4',
    authDomain: 'food-delivery-app-780f4.firebaseapp.com',
    storageBucket: 'food-delivery-app-780f4.appspot.com',
    measurementId: 'G-1V3LJ66DNJ',
  );
}
